# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # Use a Ubuntux64 Trusty Distro
  config.vm.box = "ubuntu/trusty64"

  # Create a host-only accessable network with a specific IP
  #config.vm.network "private_network", ip: "192.168.50.100"

  # Forward RMQ API and Management Console ports to host
  config.vm.network :forwarded_port, guest: 5672, host: 5672
  config.vm.network :forwarded_port, guest: 15672, host: 15672

  # Provider Configuration
  config.vm.provider "virtualbox" do |vb|
    # Set the VirtualBox Name
    vb.name = "soa-playground"
  end

  #
  # Docker Provision
  config.vm.provision "docker" do |dkr|
    # Get RMQ image from https://github.com/docker-library/rabbitmq
    dkr.pull_images "rabbitmq"

    # SoaRabbit container running RMQ w/Mgt Console and ports forwarded
    dkr.run "SoaRabbit", 
      image: "rabbitmq:3-management",
      args: "-p 5672:5672 -p 15672:15672"
  end
end
